/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NeuroVaultRegistry {
  export type DatasetStruct = {
    id: BigNumberish;
    contributor: AddressLike;
    dataCID: string;
    metadataCID: string;
    price: BigNumberish;
    registeredAt: BigNumberish;
    active: boolean;
  };

  export type DatasetStructOutput = [
    id: bigint,
    contributor: string,
    dataCID: string,
    metadataCID: string,
    price: bigint,
    registeredAt: bigint,
    active: boolean
  ] & {
    id: bigint;
    contributor: string;
    dataCID: string;
    metadataCID: string;
    price: bigint;
    registeredAt: bigint;
    active: boolean;
  };
}

export interface NeuroVaultRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LICENSE_DURATION"
      | "checkAccess"
      | "contributorEarnings"
      | "datasets"
      | "getContributorDatasets"
      | "getContributorEarnings"
      | "getDataset"
      | "licenses"
      | "listDatasets"
      | "nextDatasetId"
      | "owner"
      | "purchaseAccess"
      | "registerDataset"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "DatasetRegistered"
      | "OwnershipTransferred"
      | "PaymentDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LICENSE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "datasets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorDatasets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "licenses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listDatasets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextDatasetId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDataset",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LICENSE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "datasets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContributorDatasets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDataset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "licenses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listDatasets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextDatasetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    licensee: AddressLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: bigint,
    licensee: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    datasetId: bigint;
    licensee: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    contributor: AddressLike,
    dataCID: string,
    metadataCID: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    contributor: string,
    dataCID: string,
    metadataCID: string,
    price: bigint
  ];
  export interface OutputObject {
    id: bigint;
    contributor: string;
    dataCID: string;
    metadataCID: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentDistributedEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: bigint,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    datasetId: bigint;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NeuroVaultRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): NeuroVaultRegistry;
  waitForDeployment(): Promise<this>;

  interface: NeuroVaultRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LICENSE_DURATION: TypedContractMethod<[], [bigint], "view">;

  checkAccess: TypedContractMethod<
    [user: AddressLike, datasetId: BigNumberish],
    [boolean],
    "view"
  >;

  contributorEarnings: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  datasets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        contributor: string;
        dataCID: string;
        metadataCID: string;
        price: bigint;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getContributorDatasets: TypedContractMethod<
    [contributor: AddressLike],
    [bigint[]],
    "view"
  >;

  getContributorEarnings: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  getDataset: TypedContractMethod<
    [datasetId: BigNumberish],
    [NeuroVaultRegistry.DatasetStructOutput],
    "view"
  >;

  licenses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        licensee: string;
        datasetId: bigint;
        purchasedAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  listDatasets: TypedContractMethod<
    [],
    [NeuroVaultRegistry.DatasetStructOutput[]],
    "view"
  >;

  nextDatasetId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseAccess: TypedContractMethod<
    [datasetId: BigNumberish],
    [void],
    "payable"
  >;

  registerDataset: TypedContractMethod<
    [dataCID: string, metadataCID: string, price: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LICENSE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkAccess"
  ): TypedContractMethod<
    [user: AddressLike, datasetId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributorEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "datasets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        contributor: string;
        dataCID: string;
        metadataCID: string;
        price: bigint;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorDatasets"
  ): TypedContractMethod<[contributor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getContributorEarnings"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDataset"
  ): TypedContractMethod<
    [datasetId: BigNumberish],
    [NeuroVaultRegistry.DatasetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "licenses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        licensee: string;
        datasetId: bigint;
        purchasedAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "listDatasets"
  ): TypedContractMethod<
    [],
    [NeuroVaultRegistry.DatasetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextDatasetId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseAccess"
  ): TypedContractMethod<[datasetId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "registerDataset"
  ): TypedContractMethod<
    [dataCID: string, metadataCID: string, price: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "DatasetRegistered"
  ): TypedContractEvent<
    DatasetRegisteredEvent.InputTuple,
    DatasetRegisteredEvent.OutputTuple,
    DatasetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentDistributed"
  ): TypedContractEvent<
    PaymentDistributedEvent.InputTuple,
    PaymentDistributedEvent.OutputTuple,
    PaymentDistributedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,address,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "DatasetRegistered(uint256,address,string,string,uint256)": TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;
    DatasetRegistered: TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentDistributed(uint256,address,uint256)": TypedContractEvent<
      PaymentDistributedEvent.InputTuple,
      PaymentDistributedEvent.OutputTuple,
      PaymentDistributedEvent.OutputObject
    >;
    PaymentDistributed: TypedContractEvent<
      PaymentDistributedEvent.InputTuple,
      PaymentDistributedEvent.OutputTuple,
      PaymentDistributedEvent.OutputObject
    >;
  };
}
